=== oliver-thirtyone/turing_machine/TuringMachine/data/data/xsd/turingMachine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">

	<xsd:element name="turingMachine">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="states"       minOccurs="1" maxOccurs="1" />
				<xsd:element ref="tapes"        minOccurs="1" maxOccurs="1" />
				<xsd:element ref="alphabet"     minOccurs="1" maxOccurs="1" />
				<xsd:element ref="transitions"  minOccurs="1" maxOccurs="1" />
			</xsd:sequence>

			<xsd:attribute name="name" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

		<!-- STATES -->
		<xsd:element name="states">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element ref="state" minOccurs="1" maxOccurs="unbounded" />
				</xsd:sequence>

				<xsd:attribute name="initial-state-name" type="xsd:string" use="required" />
			</xsd:complexType>
		</xsd:element>

			<xsd:element name="state">
				<xsd:complexType>
					<xsd:attribute name="name"  type="xsd:string"  use="required" />
					<xsd:attribute name="final" type="xsd:boolean" use="optional" />
				</xsd:complexType>
			</xsd:element>

		<!-- TAPES -->
		<xsd:element name="tapes">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element ref="tape" minOccurs="1" maxOccurs="unbounded" />
				</xsd:sequence>

				<xsd:attribute name="input-tape-name"  type="xsd:string" use="required" />
				<xsd:attribute name="output-tape-name" type="xsd:string" use="required" />
			</xsd:complexType>
		</xsd:element>

			<xsd:element name="tape">
				<xsd:complexType>
					<xsd:attribute name="name"  type="xsd:string"  use="required" />
				</xsd:complexType>
			</xsd:element>

		<!-- ALPHABET -->
		<xsd:element name="alphabet">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="blank-symbol" type="symbolType" minOccurs="1" maxOccurs="1" />
					<xsd:element name="symbol"       type="symbolType" minOccurs="1" maxOccurs="unbounded" />
				</xsd:sequence>
			</xsd:complexType>
		</xsd:element>

			<xsd:complexType name="symbolType">
				<xsd:attribute name="value" type="characterType" use="required" />
			</xsd:complexType>

				<xsd:simpleType name="characterType">
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1" />
						<xsd:maxLength value="1" />
					</xsd:restriction>
				</xsd:simpleType>

		<!-- TRANSITIONS -->
		<xsd:element name="transitions">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element ref="transition" minOccurs="1" maxOccurs="unbounded" />
				</xsd:sequence>
			</xsd:complexType>
		</xsd:element>

			<xsd:element name="transition">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="tape-transition" type="tapeTransitionType" minOccurs="2" maxOccurs="unbounded" />
					</xsd:sequence>
					<xsd:attribute name="current-state" type="xsd:string" use="required" />
					<xsd:attribute name="next-state"    type="xsd:string" use="required" />
				</xsd:complexType>
			</xsd:element>

				<xsd:complexType name="tapeTransitionType">
					<xsd:attribute name="tape"         type="xsd:string"    use="required" />
					<xsd:attribute name="read-symbol"  type="characterType" use="required" />
					<xsd:attribute name="write-symbol" type="characterType" use="required" />
					<xsd:attribute name="tape-motion"  type="motionType"    use="required" />
				</xsd:complexType>

					<xsd:simpleType name="motionType">
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="L" />
							<xsd:enumeration value="R" />
							<xsd:enumeration value="S" />
						</xsd:restriction>
					</xsd:simpleType>

</xsd:schema>

=== oliver-thirtyone/turing_machine/TuringMachineTest/data/data/xml/XMLTuringParserTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<turingMachine name="Addition (Unary numeral system)" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="turingMachine.xsd">
	<states>
		<initial-state name='Q0' />
		<!-- <state name='dummy' /> -->
		<final-state name='Q1' />
	</states>

	<tapes>
		<input-tape name='T0' />
		<!-- <tape name='dummy' /> -->
		<output-tape name='T1' />
	</tapes>

	<alphabet>
		<blank-symbol value='B' />
		<symbol value='0' />
		<symbol value='+' />
	</alphabet>

	<transitions>
		<!-- Read '0': Add one '0' -->
		<transition current-state='Q0' next-state='Q0'>
			<tape-transition tape='T0' read='0' write='B' motion='R' />
			<tape-transition tape='T1' read='B' write='0' motion='R' />
		</transition>

		<!-- Read '+': Do nothing -->
		<transition current-state='Q0' next-state='Q0'>
			<tape-transition tape='T0' read='+' write='B' motion='R' />
			<tape-transition tape='T1' read='B' write='B' motion='S' />
		</transition>

		<!-- Read 'B': Go to final state -->
		<transition current-state='Q0' next-state='Q1'>
			<tape-transition tape='T0' read='B' write='B' motion='S' />
			<tape-transition tape='T1' read='B' write='B' motion='S' />
		</transition>
	</transitions>

</turingMachine>
